language: go
go:
  - 1.5
  - 1.6
  - tip
install:
  - go get github.com/Masterminds/glide
  - go get golang.org/x/lint/golint
before_script:
script:
  - glide install
  - GO15VENDOREXPERIMENT=1 go build .
  - GO15VENDOREXPERIMENT=1 go test $(glide novendor)
  - go vet . ./tftp
  - golint .
  - golint tftp
